baseURL = "/"
languageCode = "en"
title = "Leela Chess Zero"
# themesDir = "../.."
theme = "whisper"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30


[[menu.main]]
    name = "Play"
    url = "/play/quickstart/"
    weight = 20

[[menu.main]]
    name = "Watch"
    url = "/watch/"
    weight = 30

[[menu.main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 40

[[menu.main]]
    name = "Development"
    url = "/dev/"
    weight = 50

[[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 60

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 70

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 80



[params]
  lc0version="v0.23.1"
  google_analytics_id=""
  # homepage_button_link = '/docs'
  # homepage_button_text = 'Download'
  homepage_intro = 'Whisper is a documentation theme built with Hugo. The design and functionality is intentionally minimal.'
  homepage_image = '/images/logo_v2.svg'
  mainSections = ["play", "watch", "contribute", "dev", "community", "blog", "about"]
  [[params.homepage_button]]
    link = "/play/download"
    text = "Download"
  [[params.homepage_button]]
    link = "/play/quickstart"
    text = "Quick start"

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Hugo Whisper Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo.svg"
      standard  = "/images/logo.svg"
